language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

script:
  - nosetests

after_success:
  - codecov

services:
  - docker

before_install:
  - docker pull couchdb
  - curl -X PUT http://127.0.0.1:5984/_users
  - curl -X PUT http://127.0.0.1:5984/_replicator
  - curl -X PUT http://127.0.0.1:5984/_global_changes
  - docker run couchdb --restart=always -d --name couchdb -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=pass
