language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

script:
  - nosetests

after_success:
  - codecov

services:
  - couchdb

before_install:
  - curl http://admin:pass@127.0.0.1:5984/
